### PR TITLE
8.0.x

### PR DESCRIPTION
**Pull request by amaria**
Changes in this request...
- Removes the entity_reference dependency
- Moves the form to a static attach() function on AdministrationForm class, so that it can be used by both the global settings and field settings form.
- Removes ConfigurableEntityconnectItem.php and the hook_field_info_alter that used it. Instead...
- Adds a hook_form_FORM_ID_alter() for the 'field_config_edit_form' to simply add the entity connect settings form as third party settings on the entity_reference field. (This is the recommended way of adding settings to a field owned by another module.)

### CODE REVIEW

**Comment by jygastaud** [comment]
Thanks again.

Just a note at the moment: I see some space missing between `=>` en `t()`.
I hope I can give a try to your PR tomorrow.

**Comment by jygastaud** [comment]
Thanks again @amaria 
I tested the PR as is and it looks to work fine.

Just a note at the moment: I see some space missing between `=>` en `t()`
Will try to made a more deep review asap.

**Comment by amaria** [comment]
Oops, find/replace error. Ok, I added the spacing.
Thanks!

**Comment by jygastaud** [comment]
I just merged your PR.
Thanks.

Go to the next step ;)

**Pull request merged**
