### PR TITLE
8.0.x

### PR DESCRIPTION
**Pull request by amaria**
This PR contains the fully functioning module in Drupal 8. Please review and let me know if you find any issues.

This works with just about any entity reference field, and there are a lot of them in D8. But I've only tested with...
- Node
- User
- Taxonomy Term
- Vocabulary
- Block
- Shortcut link

Here's what's left to be done:
- Test the views handler functionality, and fix any problems.
- Test with field collection and eck, and fix any problems.

### CODE REVIEW

**Comment by jygastaud** [comment]
Wow thank you very much @amaria.
That sounds amazing.

If it works for all entity you mentioned, I think we really can produce a first alpha or beta release on d.o

I will try to test it soon.

**Comment by dom18fr** [comment]
Works fine to me.
Quickly tested using reference to node, in a multivalued field.

**Comment by amaria** [comment]
Ok @jygastaud. If you need a co-maintainer you can add me. So I could also help with version 7.

@dom18fr Thanks for testing!

**Comment by jygastaud** [comment]
Thanks again @amaria for your great contribution.
I added your account (hope it's the good one ;)) in drupal.org as a co-maintener.

I also create a 8.x-2.x branch and created a first alpha tag.
It should be available soon.

I will remove the 8.0.x branch from Github too and work should be done from 8.x-2.x branch now.

**Pull request merged**
